FROM nvidia/cuda:9.0-base-ubuntu16.04

RUN apt-get update
RUN apt-get install -y \
    wget \
    curl \
    make \
    build-essential \
    cuda-command-line-tools-9-0 \
    cuda-cublas-9-0 \
    cuda-cufft-9-0 \
    cuda-curand-9-0 \
    cuda-cusolver-9-0 \
    cuda-cusparse-9-0 \
    curl \
    libcudnn7=7.0.5.15-1+cuda9.0 \
    libfreetype6-dev \
    libpng12-dev \
    libzmq3-dev \
    pkg-config \
    rsync \
    software-properties-common \
    unzip \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libcupti-dev \
    python3-numpy \
    python3-dev \
    python3-pip \
    python3-wheel \
    python3-pyaudio \
    ffmpeg


# install python 3.6
RUN wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz
RUN tar xvf Python-3.6.4.tgz
RUN cd Python-3.6.4 && ./configure && make && make install && cd ..
RUN rm -rf Python-3.6.4.tgz

# RUN apt-get install software-properties-common -y
# RUN add-apt-repository ppa:jonathonf/python-3.6 -y\
# &&  apt-get update -y\
# &&  apt-get install python3.6 -y


RUN python3.6 -m pip install --upgrade pip
RUN python3.6 -m pip install jupyter
RUN mkdir /root/.jupyter
RUN echo "c.NotebookApp.ip = '*'" \
         "\nc.NotebookApp.open_browser = False" \
         "\nc.NotebookApp.token = ''" \
         > /root/.jupyter/jupyter_notebook_config.py

RUN python3.6 -m pip install numpy \
    pandas \
    matplotlib \
    tensorflow \
    h5py \
    keras \
    pydot \
    ipython \
    scipy \
    pyconfig \
    music21 \
    librosa \
    faker \
    tqdm \
    babel \
    pydub \
    pyaudio \
    six \
    resampy \
    pillow \
    ipykernel

RUN python3.6 -m ipykernel.kernelspec

# --- DO NOT EDIT OR DELETE BETWEEN THE LINES --- #
# These lines will be edited automatically by parameterized_docker_build.sh. #
# COPY _PIP_FILE_ /
# RUN pip --no-cache-dir install /_PIP_FILE_
# RUN rm -f /_PIP_FILE_

# Install TensorFlow GPU version.
RUN pip --no-cache-dir install \
    http://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.0.0-cp27-none-linux_x86_64.whl
# --- ~ DO NOT EDIT OR DELETE BETWEEN THE LINES --- #

# Set up our notebook config.
COPY jupyter_notebook_config.py /root/.jupyter/

# Copy sample notebooks.
COPY notebooks /notebooks

# Jupyter has issues with being run directly:
#   https://github.com/ipython/ipython/issues/7062
# We just add a little wrapper script.
# COPY run_jupyter.sh /

# For CUDA profiling, TensorFlow requires CUPTI.
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH


## Cleanup ##
RUN apt-get clean && apt-get autoclean && apt-get autoremove 
RUN apt-get purge lib*-dev build-essential -y

# ENTRYPOINT ["bash", "http://0.0.0.0:8888"]
#  docker run -p 8888:8888 --name deep01 --rm -it dscience:latest
# we need to run "jupyter-notebook --allow-root" from inside the container
