version: '3.5'

services:
  api:
    image: dscience
    environment:
      NODE_ENV: development
    ports:
      - 8888:8888
    volumes:
      - .:/usr/src/model  # map this current directory with /usr/src/api in the docker container
    command: jupyter-notebook --allow-root
